name: SRx264_l1_v2
discription: SRx264, mv, gan, fm 48
scale_factor: 2
mv: false
gan: false

datasets: 
  train:
    name: vimeo90k
    path: ../dataset/vimeo90k
    txt_path: ../dataset/vimeo90k/sep_trainlist.txt
    lr_dir: ../dataset/vimeo90k/lr
    hr_dir: ../dataset/vimeo90k/hr
    train_ratio: !!float 8e-1
    use_shuffle: false
    batch_size: 16
    val_batch_size: 12
    color: RGB
  test:
    name: vimeo90k
    path: ../dataset/vimeo90k
    txt_path: ../dataset/vimeo90k/sep_testlist.txt
    lr_dir: ../dataset/vimeo90k/lr
    hr_dir: ../dataset/vimeo90k/hr
    batch_size: 16

network_G:
  net: SRX264
  version: v2
  feature_maps: 48
  in_nc: 9
  out_nc: 9

network_D:
  net: NLayerDiscriminator
  in_nc: 3
  nf: 64
  nLayer: 3

train:
  epoch: 10
  multiple: 255
  lr_G: !!float 1e-4
  lr_D: !!float 1e-4
  pixel_weight: !!float 1e-2
  pixel_criterion: l1
  feature_weight: 1
  feature_criterion: l1
  gan_weight: !!float 5e-3
  mix_loss: false
  mv_loss: false
  mv_weight: !!float 2e-2